# Generated by Django 5.2.8 on 2025-11-10 21:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('contacto', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('conductividad', models.DecimalField(decimal_places=3, help_text='W/(m·K)', max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='SistemaClimatizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=100, unique=True)),
                ('eficiencia_nominal', models.DecimalField(decimal_places=2, help_text='COP/EER', max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='TipoProyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('fecha_inicio', models.DateField()),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.cliente')),
                ('sistemas', models.ManyToManyField(related_name='proyectos_asociados', to='gestion.sistemaclimatizacion')),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestion.tipoproyecto')),
            ],
        ),
        migrations.CreateModel(
            name='Muro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ubicacion', models.CharField(max_length=50)),
                ('superficie', models.DecimalField(decimal_places=2, help_text='m²', max_digits=6)),
                ('espesor_total', models.DecimalField(decimal_places=2, help_text='metros', max_digits=5)),
                ('material_aislante', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestion.material')),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='muros', to='gestion.proyecto')),
            ],
        ),
        migrations.CreateModel(
            name='ResultadoCEV',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calificacion', models.CharField(choices=[('A+', 'A+'), ('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E'), ('F', 'F')], default='F', max_length=2)),
                ('consumo_energia_anual', models.DecimalField(decimal_places=2, help_text='kWh/m² año', max_digits=10)),
                ('fecha_calculo', models.DateField(auto_now_add=True)),
                ('proyecto', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='gestion.proyecto')),
            ],
        ),
    ]
