# Generated by Django 5.2.8 on 2025-11-19 02:34

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='muro',
            name='espesor_total',
        ),
        migrations.RemoveField(
            model_name='resultadocev',
            name='fecha_calculo',
        ),
        migrations.AddField(
            model_name='resultadocev',
            name='fecha_calificacion',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='contacto',
            field=models.CharField(max_length=100, unique=True, verbose_name='Email de Contacto'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='nombre',
            field=models.CharField(max_length=100, verbose_name='Nombre/Razón Social'),
        ),
        migrations.AlterField(
            model_name='material',
            name='conductividad',
            field=models.DecimalField(decimal_places=3, max_digits=5, verbose_name='Conductividad Térmica (W/mK)'),
        ),
        migrations.AlterField(
            model_name='material',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='muro',
            name='material_aislante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='muros', to='gestion.material'),
        ),
        migrations.AlterField(
            model_name='muro',
            name='superficie',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Superficie (m²)'),
        ),
        migrations.AlterField(
            model_name='muro',
            name='ubicacion',
            field=models.CharField(max_length=50, verbose_name='Ubicación (Norte, Sur, etc.)'),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proyectos', to='gestion.cliente'),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='fecha_inicio',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='nombre',
            field=models.CharField(max_length=200, verbose_name='Nombre de la Vivienda/Proyecto'),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='sistemas',
            field=models.ManyToManyField(related_name='proyectos', to='gestion.sistemaclimatizacion'),
        ),
        migrations.AlterField(
            model_name='resultadocev',
            name='calificacion',
            field=models.CharField(choices=[('A+', 'A+ (Excelente)'), ('A', 'A (Muy Bueno)'), ('B', 'B (Bueno)'), ('C', 'C (Estándar)'), ('D', 'D (Malo)')], max_length=2),
        ),
        migrations.AlterField(
            model_name='resultadocev',
            name='consumo_energia_anual',
            field=models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Consumo Anual (kWh/m²)'),
        ),
        migrations.AlterField(
            model_name='resultadocev',
            name='proyecto',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='resultados', to='gestion.proyecto'),
        ),
        migrations.AlterField(
            model_name='sistemaclimatizacion',
            name='eficiencia_nominal',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=5, verbose_name='Eficiencia Nominal (COP/SCOP)'),
        ),
        migrations.AlterField(
            model_name='sistemaclimatizacion',
            name='tipo',
            field=models.CharField(max_length=100, verbose_name='Tipo de Sistema'),
        ),
        migrations.AlterField(
            model_name='tipoproyecto',
            name='nombre',
            field=models.CharField(max_length=50),
        ),
    ]
