# Generated by Django 5.2.8 on 2025-11-22 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0002_remove_muro_espesor_total_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='material',
            options={'verbose_name_plural': 'Materiales'},
        ),
        migrations.AlterModelOptions(
            name='muro',
            options={'verbose_name_plural': 'Muros'},
        ),
        migrations.AlterModelOptions(
            name='proyecto',
            options={'ordering': ['-fecha_inicio'], 'verbose_name_plural': 'Proyectos'},
        ),
        migrations.AlterModelOptions(
            name='resultadocev',
            options={'verbose_name': 'Resultado CEV', 'verbose_name_plural': 'Resultados CEV'},
        ),
        migrations.AlterModelOptions(
            name='sistemaclimatizacion',
            options={'verbose_name_plural': 'Sistemas de Climatización'},
        ),
        migrations.AlterModelOptions(
            name='tipoproyecto',
            options={'verbose_name_plural': 'Tipos de Proyecto'},
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='sistemas',
            field=models.ManyToManyField(blank=True, related_name='proyectos', to='gestion.sistemaclimatizacion'),
        ),
    ]
